### ISSUE TITLE
AOEHD 4.0 patch

### ISSUE THREAD

**Issue by FrankConnor** [crimsoncantab/aok-hotkeys#36]
is it just me or does the editor no longer work with the 4.0 patch? will this editor be updated?

I have no other way of gettign my azerty grid setup going, since the in-game editor won't accept conflicting hotkeys

**Comment by crimsoncantab** [comment]
I apologize, I've been inactive in the AoEHD community so I haven't been keeping up with recent patch changes. However, this looks like it's an issue with the game itself:

http://steamcommunity.com/app/221380/discussions/0/598199244893850921/

Is that thread still valid?

**Comment by iopq** [comment]
The game doesn't seem to use the .hki files anymore?

**Comment by crimsoncantab** [comment]
Ah, interesting. That's a big change. I'll have to look into the new hotkey file format. Thanks for bringing this up.

**Comment by petekalo** [comment]
The new folder for HD 4.0 is C:/Program Files/Steam/steamapps/common/Age2HD/profiles/

**Comment by crimsoncantab** [comment]
Merged and deployed. Thanks!
