### ISSUE TITLE
Unable to use groups after 9- clicking disabled doesn't work

### ISSUE THREAD

**Issue by SRGOM** [crimsoncantab/aok-hotkeys#38]
Are they really just *disabled*? If so, maybe remove them because this is probably the first place I've seen any reference to them anyway...

**Comment by crimsoncantab** [comment]
The hotkeys existed in game for earlier versions of the game, but aren't available for most recent versions of HD.

**Comment by SRGOM** [comment]
Oh I see. Didn't know that.
