### ISSUE TITLE
AOE2 HD FE 4.0 or 4.2 hotkeys

### ISSUE THREAD

**Issue by jsingh214** [crimsoncantab/aok-hotkeys#40]
Hi there,

Is there any plans to add support for AOE2 HD FE 4.0 or 4.2 hotkeys? Thanks!

**Comment by crimsoncantab** [comment]
It's somewhat unclear, but Version "HD3.0" works for 3.0+, including most recent versions. Hotkeys haven't changed since 3.0. Do note, however, that 4.0 changed the location of the hotkeys file to "C:\Program Files (x86)\Steam\SteamApps\common\Age2HD\profiles\player1.hki"

**Comment by jsingh214** [comment]
Ah ok want sure if with the introduction of feitoria they had changed


Sent from my Verizon Wireless 4G LTE DROID
On Jan 7, 2016 11:00 PM, crimsoncantab <notifications@github.com> wrote:

It's somewhat unclear, but Version "HD3.0" works for 3.0+, including most recent versions. Hotkeys haven't changed since 3.0. Do note, however, that 4.0 changed the location of the hotkeys file to "C:\Program Files (x86)\Steam\SteamApps\common\Age2HD\profiles\player1.hki"

**Comment by crimsoncantab** [comment]
Shoot good call. I'll have to look into it.

Is there a new hotkey assignment specifically for the feitoria?

I expect you'll be able to edit all the other keys still, but you'll have to do that one with the in-game editor.

Honestly, I haven't had much time to play AoK in quite a while, so I'm behind on the times. Sorry I'm letting the age community down :(.

**Comment by jsingh214** [comment]
Oh it's no worries I just figure it'd be good info for you to know, at the moment I'm unusure which key assignment Feitoria has as I'm at work but I'll let you know. And actually I'm not sure if it does at the moment allow you to edit and put the hotkey file in since when you go to do it with the HD 3.0 one it will just reset to default keys acting like its not there. And when you upload a 4.0 set of hotkeys to the website it will say something along the lines of cannot recognize file format which makes sense. Let me know if you need me to clarify anything or need anything else from me as I'm terrible at explaining XD


________________________________

**Comment by crimsoncantab** [comment]
Okay, they may have completely changed the hotkey file format with 4.0. I'll have to look into it.

**Comment by crimsoncantab** [comment]
Just an update: it looks like with version 4.0 the default hotkeys file is now called "player0.hki" instead of "player1.hki". I tested that out, you should be able to use the hotkeys from the editor if you rename it to have the "0" instead.

**Comment by crimsoncantab** [comment]
4.4 is now supported.

They added more than Feitoria; there was Genitour (archery range), Siege Tower (workshop), and they added a build hotkey for palisade gate. They also changed the code for Longboat, and added Caravel to it.

**Comment by jsingh214** [comment]
thank you crimson! [&#X1f603]


________________________________

**Comment by jsingh214** [comment]
Its funny  because someone on reddit aoe2 asked about your website if it works with hotkeys XD I let them know it does now. Thanks again, sorry if this took a lot of time

________________________________

**Comment by crimsoncantab** [comment]
Nah, it was fun. Just finding the time to do it is the hard part.

It's quite an interesting puzzle to reverse engineer the .hki file; it's both binary and compressed, and you can't just decompress it with a regular tool because it's missing some of the file header. And figuring out where each of the new hotkeys is takes a bit of tinkering with a hex editor.

**Comment by jsingh214** [comment]
I know a decent amount about coding, but that sounds difficult haha. I always wondered how you managed to do all this stuff and be able to make generatable hotkey files. What a homie! [&#X1f603]


________________________________
