### ISSUE TITLE
Hello I use viper hotkeys on

### ISSUE THREAD

**Issue by razvysb93** [crimsoncantab/aok-hotkeys#43]
Website: https://aokhotkeys.appspot.com/
Issue: the viper hotkeys
Version:HD 4.4+ select gropup hotkeys not working

**Comment by razvysb93** [comment]
Oh sorry , didn't observed that there are two different hotkeys:
Create Group 
and 
Select Group , I set only Create Group

**Comment by crimsoncantab** [comment]
Glad you figured it out. Closing the case for now.
