### ISSUE TITLE
Can't assign "Shift" to economic build command

### ISSUE THREAD

**Issue by AXMIM** [crimsoncantab/aok-hotkeys#45]
I did like to assign Shift to economic build command.

**Comment by AXMIM** [comment]
Nevermind, using javascript, I was able to acheive it from behind. Thanks for your tool.

**Comment by crimsoncantab** [comment]
Glad you found a workaround.

Does that actually work in-game, though? I would expect using a modifier key itself as a hotkey would do nothing or mess up any hotkeys with that modifier set...
