### ISSUE TITLE
Decompressed version of Hotkey file

### ISSUE THREAD

**Issue by gregstein** [crimsoncantab/aok-hotkeys#50]
Hello,

Could you please share the decompressed version of the hotkey file.

Thank you,

**Comment by crimsoncantab** [comment]
@gregstein , what version of the file?

Are you aware that the file is in binary format? Even uncompressed, it's still unreadable without a hex editor, and even then you need to know how the binary data is structured.

If you have a particular *.hki file you want to decompress, you can use the [decompress() method](https://github.com/crimsoncantab/aok-hotkeys/blob/master/modules/hkizip.py#L19) with the compressed file as input.

The hkizip module that contains that method is runnable; you can create a decompressed file by running
`hkizip.py d < {infile} > {outfile}`
where {infile} is the path to your compressed file, and {outfile} is what you want to call the decompressed output.

**Comment by gregstein** [comment]
Thank you!!!
