### ISSUE TITLE
Read Hotkey values from a player0.hki

### ISSUE THREAD

**Issue by gregstein** [crimsoncantab/aok-hotkeys#51]
Hello again,
(I apologize for starting the second ticket in the row)
So I would like to read all hotkey values from player0.hki and have them saved into text file. I attempted that in C# but sadly I got nowhere. You also suggested me to use `hotkeys.py d < player0.hki > player0.hki` Which I have typed to Pycharm Terminal and the output returned an Text file. BTW, I have never touched Python before so I would appreciate if you could help me out with this one. 

Thank you so much,

**Comment by gregstein** [comment]
Thank you! I have managed to decompress the *.dat file of the hotkey using offzip method. 

Here is the binary file in Hex:
![Binary Hotkey](https://image.prntscr.com/image/10_Q6qlATZ2A6PU2O3TtIg.png)

**Comment by crimsoncantab** [comment]
@gregstein , they're not exactly "pointers" so much as "markers." The decompressed file is an array of 12-byte c struct objects, occasionally separated by 4-byte "headers" for each section of the hotkey list. If you look at [lines 609-610](https://github.com/crimsoncantab/aok-hotkeys/blob/7a1587d2489a0825a5c7c2b1e1618b79255caf96/modules/hotkeys.py#L610), they define the struct (in python terms):

- The first 4 bytes are an unsigned int representing the keyboard code that the hotkey is assigned to.
- The next 4 bytes are a signed int representing the magic "id"s that the `hk_ids` dictionary holds.
- The next 3 bytes are boolean flags for whether shift/ctrl/alt are part of the hotkey, and the last byte is padding for the word boundary.

Hope that helps.

**Comment by gregstein** [comment]
WOW!! Thank you so much!!! This is reallly helpful! <3
