### ISSUE TITLE
Support for WK

### ISSUE THREAD

**Issue by rwh03001** [crimsoncantab/aok-hotkeys#57]
This is such an amazing tool, and AoC needed it very badly.  Thanks for putting it together.  Would it be possible to create a version compatible with Voobly's WK mod?

**Comment by Jineapple** [comment]
What exactly do you mean by "compatible"? You can use these hotkey files for WK already. There are a few small restrictions on it (The changed control groups don't work, elephants share a hotkey with camels instead of having a seperate one) but that's it.

**Comment by rwh03001** [comment]
If I go into my WK folder and load my player1.hki file, it says the file type is not recognized.

**Comment by crimsoncantab** [comment]
Ah, yep, that's an issue. Any hki file you download should work on WK but
you can't upload a WK file. Could you attach the WK .hki file to this case?

**Comment by rwh03001** [comment]
Happy to.  (I zipped it because I can't upload an hki directly)
[WK hki zip.zip](https://github.com/crimsoncantab/aok-hotkeys/files/2898250/WK.hki.zip.zip)

**Comment by crimsoncantab** [comment]
I don't have WK installed; does it not have hotkey entries for control groups? When I added a version for WK using your .hki file, it's showing all the control group hotkeys as disabled. Is that expected, @rwh03001 ?

**Comment by crimsoncantab** [comment]
Update is out to support WK, feel free to reopen if something looks wrong, @rwh03001
