### ISSUE TITLE
Can't open any preset . March 2019

### ISSUE THREAD

**Issue by franciscofruiz** [crimsoncantab/aok-hotkeys#58]
I tried to load several times presets as https://aokhotkeys.appspot.com/presets/get/26006 (viperhotkeys) and other ones, but the site is just loading the game default hotkeys, I tested on chrome 72.x, Firefox 65 and Edge  42.17134.1.0 Microsoft EdgeHTML 17.17134. I cleaned cookies and nothing worked. :(

**Comment by crimsoncantab** [comment]
Hmm, unfortunately I'm not able to reproduce the problem in chrome 72.x, FF 60.x, or Edge 42.17134.1.0. I click on the viperhotkeys link you provided and it correctly shows vipers hotkeys in the editor page. I am also able to switch to, e.g., grid hotkeys from the Presets page and see the hotkeys change in the editor. Could you try again and make sure you're still seeing the issue, please?

**Comment by franciscofruiz** [comment]
You are right, I didnt check all the hotkeys, I was based on settings, cntrl groups(were disabled) and cntr+key to go to economic buildings(were default ones).
Excuses, thank you for your response and great job :).

**Comment by crimsoncantab** [comment]
Glad it's working for you, Thanks for verifying :)
