### ISSUE TITLE
AoE2: Definite Edition support please

### ISSUE THREAD

**Issue by DavidGretzschel** [crimsoncantab/aok-hotkeys#59]
Already making a great profile, that incorporates all the extra keys in an ergonomic manner.
https://forums.ageofempires.com/t/deciding-on-hotkeys/62861/4

Would like to upload it here.

**Comment by crimsoncantab** [comment]
Could you attach a sample *.hki file that you're using for DE?

**Comment by crimsoncantab** [comment]
Scratch that, I'm assuming that's your *.hki file in the link you sent.

**Comment by DavidGretzschel** [comment]
If it should help working with the default-hotkeys, here they are:
There are preset hotkey layouts to choose from Definitive Hotkeys, Left-Handed Hotkeys, Classic Hotkeys, HD Hotkeys.

https://1drv.ms/u/s!AnW9DTwVxi8MhPoibCsaP3n-XJ6Lxw?e=0JOM71

**Comment by crimsoncantab** [comment]
@DavidGretzschel sorry it took so long....they added a looooooot of hotkeys. Unfortunately my process right now for adding new hotkeys to the site is pretty manual.

DE is live on the site: https://aokhotkeys.appspot.com/

**Comment by crimsoncantab** [comment]
Looks like uploading for DE files is not working...looking into it.

**Comment by crimsoncantab** [comment]
Working now...I think it might have been a caching issue.

**Comment by crimsoncantab** [comment]
Fixed.

**Comment by DavidGretzschel** [comment]
Thank you very much. This allows for much fancier keybindings than the inbuilt editor.
I shall do some very fancy things with it soon!
