### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by HellsingUltimate** [crimsoncantab/aok-hotkeys#60]
Hi i play on aoe2 DE couldn't change my hotkey "ctrl-shift-B" to select all my barracks to "maj-A" (azerty keyboard) even tho i don't have any other hotkey using it, so i wanted to use Hotkey Editor BUT after selecting my .hki file and clicking "edit" i had a msg error :
"File format not recognized: Unrecognized file format, header: 40400000, length: 4644"
could u help me plz ?

**Comment by crimsoncantab** [comment]
@HellsingUltimate thanks for the report. Can you attach the .hki file that you used to get that error, please?

**Comment by swampservers** [comment]
I have the same issue, it doesn't work for AOE2DE
https://drive.google.com/open?id=1rmZeHBV8qDUk9fschcC5SrVnOn0ULlF0

**Comment by crimsoncantab** [comment]
@HellsingUltimate @swampservers thanks for letting me know about this. They added another secret hotkey for the Chieftains tech that doesn't even show up in the in-game editor. Give it another shot, I just tried it with the file that @swampservers provided.
