### ISSUE TITLE
error when uploading aoe2de HK

### ISSUE THREAD

**Issue by harooooo1** [crimsoncantab/aok-hotkeys#61]
Getting the following error when uploading a aoe2 DE hotkey file:

File format not recognized: Unrecognized file format, header: 40400000, length: 4664

I believe the cause of this error is that in the latest aoe2de patch (which was released 20ish days ago), hotkey file structure was changed, so that the gate rotation hotkeys got it's own tab, as well as some other changes. So could you please update the website, i really like using it. Thanks.

**Comment by crimsoncantab** [comment]
Thanks for bringing this up. I'll try to get a fix out soon.

**Comment by crimsoncantab** [comment]
@harooooo1 the infamous Auto Scout was the culprit. Fixed & deployed
