### ISSUE TITLE
How do you have multiple hotkeys for a single command?

### ISSUE THREAD

**Issue by danyyy** [crimsoncantab/aok-hotkeys#63]
Hello! Sorry if this is not the right place to post this but im using the hotkey editor for aoe2 and i was wondering how you add multiple keys for the same command.  I really want to have both "k" and "p" for the Economic Buildings. Thank you!

**Comment by crimsoncantab** [comment]
That's currently impossible to do without changes to the game itself. The
game only stores one binding per hotkey; we wouldn't be able to generate a
hotkey file that the game could read unless it explicitly had a 2nd hotkey
for the same function (Go to Town Center, Go to Next Idle Mil/Vill, & Go to
Last Notification are examples of this).

**Comment by crimsoncantab** [comment]
@danyyy a potential workaround would be to [remap the relevant keyboard keys](https://www.pcmag.com/how-to/how-to-remap-your-keyboard), so, say, you had your "p" key mapped to "k", then you could just use "k" in your hotkeys settings and both keys would work. But then you have the issue of when you want to type a "p" in chat...

Kind of curious why you need to map a hotkey to multiple keys... p and k are pretty close to each other on a querty keyboard layout, so what do you gain from binding economic buildings to both?

**Comment by danyyy** [comment]
Thats a good idea! 

I'm using a advanced hotkey layout called "The Core" in Starcraft 2, which is focused on ergonomic and speed and since i really like it, i thought i would try to make a similar layout to age of empires 2.

 The idea with multiple keys for example "k" and "p" as economic buildings is that it is faster and less exhausting to press two buttons instead of holding down or using the same finger to tap twice.

so if a house is built on "k" and you open the economics building tab with only "k" you would tap
or hold down the "k" key to build the farm.

But if you use both "k" and "p" you would press p + k with two different fingers to perform the same action instead of using one finger twice.

It also makes it easier if there is longer distant between certain buildings.
if "build mill" is on "OMLJUD" (the key on the right side of "Å")

instead of pressing "K+ OMLJUD" (which is pretty far away)
You could press "p + OMLJUD" as an alternative, using fingers that are natural positioned in that area of the keyboard to perform the action.


![TheCore6eFingers](https://user-images.githubusercontent.com/1843076/78958126-81af3a00-7ae7-11ea-9549-25fc6f40da3f.PNG)

**Comment by crimsoncantab** [comment]
Ohhh cool! Yea that makes sense. Thanks for the explanation. Do you use a separate keyboard for hotkeys? I use a half-keyboard with easily-rebindable keys, so that it doesn't affect my regular keyboard for typing in chat or using other applications besides Age. So that makes rebinding + macros much easier to be aggressive about.

**Comment by danyyy** [comment]
I see, currently i only use one keyboard, i might use a remapping tool with profiles so i can easily switch for different games/tasks.
