### ISSUE TITLE
again the same error, file format unrecognized

### ISSUE THREAD

**Issue by harooooo1** [crimsoncantab/aok-hotkeys#64]
Hello, i am writing again, last time the Auto scout hotkey was the issue, probably this patch the Flaming camel hotkey might be the new thing causing the format to be unrecognized.

**Comment by crimsoncantab** [comment]
@harooooo1 thanks for the heads up. Fixed & deployed. As you accurately guessed, flaming camels blew up the site.

I have a pretty streamlined process for updating when there are new hotkeys. Unfortunately, however, it still requires a code change and I don't have a good way of automatically detecting when a new update introduces new hotkeys into the *.hki file.
