### ISSUE TITLE
New Hotkeys from anniversary patch

### ISSUE THREAD

**Issue by harooooo1** [crimsoncantab/aok-hotkeys#68]
Hello, just writing this to inform you that the latest November patch added some new hotkeys to aoe2de, related to Select All Trade units, and also some new functionality with select water army etc..

Those need to be added to make the aokhotkeys editor compatible with the newest hotkey files

**Comment by harooooo1** [comment]
Created a new hotkey entry to quickly “Go to King” when playing the Regicide game mode.
Created a new hotkey entry that allows you to “Select all Trade Units.”
The “Select all visible Military Units” hotkey can now be used to select visible warships if no land units are also visible or by pressing the hotkey twice.

- info from patch notes

**Comment by crimsoncantab** [comment]
@harooooo1 thanks for staying on top of this. Should be fixed now. I've debated allowing the site to accept new files with new unrecognized hotkeys, and downgrading to the latest version that the site has. It would be failing silently, but it would allow people to at least edit most hotkeys when they upload a file from an updated version of the game.
