### ISSUE TITLE
AOE2DE hotkeys not working

### ISSUE THREAD

**Issue by Gertsch** [crimsoncantab/aok-hotkeys#70]
Hey all,

when I download the hki file and place it in the profiles folder, it doesn't show up in the game.
I also tried creating a new hotkey profile in-game and replacing this then with the generated one.
But it doesn't work.
Any thoughts?

**Comment by crimsoncantab** [comment]
Hey @Gertsch I ran across this a few months back, and realized that at some point, DE requires you to update the hki file in two places. See this forum thread: https://www.aoezone.net/threads/anyone-know-where-the-hotkey-files-are-for-aoe2-de.162649/

I thought I had updated instructions on the site's landing page, but looks like I haven't. Need to do that.

Let me know if the info in that aoezone thread doesn't work for you (I think you might need an account to see the posts that have an answer).
