### ISSUE TITLE
[Request] Any way to load a Hot Key File and Edit it

### ISSUE THREAD

**Issue by KarthikAbiram** [crimsoncantab/aok-hotkeys#71]
First of all thanks for creating this nice tool - this is very helpful to get a bird's eye view of all hot keys and edit them.

One feature request - currently I am able to edit the hot key settings and save to file. Is there any way to load a hotkey file, edit it and then download it back with the changes?

**Comment by crimsoncantab** [comment]
Hi @KarthikAbiram!

This functionality already exists. If you go to the [main page](http://aokhotkeys.appspot.com/), you can upload a file and edit it here:
![image](https://user-images.githubusercontent.com/4349440/127751067-72fe3bcc-ded3-42b0-83d8-449428b587ea.png)
