### ISSUE TITLE
Support for Community Patch v1.6

### ISSUE THREAD

**Issue by pablocanones** [crimsoncantab/aok-hotkeys#72]
Hello.
I'm one of the developers of the mod Community Patch v1.6 in Voobly,
https://www.voobly.com/gamemods/mod/1533/v16-Game-Data

The reason I'm writting is because we've added to the mod several new hotkeys, for the new units and some technologies. In doing so, the hki files our mod uses are not compatible with your website.
Would it be possible to add support for our mod in your page? What information would you need?

Thanks a lot,
Pancrol

**Comment by crimsoncantab** [comment]
Hey @pablocanones !

If you can share a *.hki file generated by your mod, and a <game-dir>\resources\en\strings\key-value\key-value-strings-utf8.txt so I can pull out the string names for each hotkey, I can add support for your mod.

**Comment by pablocanones** [comment]
Hello, thanks a lot for answering.
Here are links to the hki file and the language file. The mod's structure is identical to the original Wololo Kingdoms:
https://www.dropbox.com/s/g0po6437f7op4zx/player1.hki?dl=0
https://www.dropbox.com/s/o8entg2zeyhsyf9/language.ini?dl=0
Don't hesitate to ask if you have doubts.
Regards

**Comment by crimsoncantab** [comment]
Hey @pablocanones , I was able to get the language.ini file, but not the player1.hki file. Dropbox said it had been deleted. Could you re-share, please?

**Comment by pablocanones** [comment]
I promise I didn't move the file:
https://www.dropbox.com/s/6t6fhcst0bmdtdu/player1.hki?dl=0
Here it is also on Drive:
https://drive.google.com/file/d/1ivmZPZyoxvjfkboJ_OuFb7NjYCQRF-WY/view?usp=sharing

**Comment by crimsoncantab** [comment]
Got it, thanks! I'll take a look at this in the next few days.
----
Loren McGinnis
