### ISSUE TITLE
Can't edit DE hotkeys

### ISSUE THREAD

**Issue by fpracing1** [crimsoncantab/aok-hotkeys#73]
Hi, I just want to convert my DE hotkeys to HD and AOC version but I can't upload my hotkeys file. The page say 

> "File format not recognized: Unrecognized file format, header: 40400000, length: 4832"

 My settings was the default DE hoykeys. I tried this today, 31/10/2021. Thank you.

**Comment by crimsoncantab** [comment]
Thanks for getting this reported. I'll take a look tonight - might be that
they added new hotkeys to DE.
