### ISSUE TITLE
How to parse a decompressed hotkey file?

### ISSUE THREAD

**Issue by gregstein** [crimsoncantab/aok-hotkeys#74]
Hello,

So I decompressed a hotkey file 
`py hkizip.py d < player1.hki > player.txt`

But my attempts to parse it into a json file have failed with this command
`py hkparse.py < player.txt > player.json`

I get **TypeError: a bytes-like object is required, not 'str'**  I'm certainly doing something wrong. Could you help me with this one please?

Thanks for the amazing library and the continuous support!!!!

**Comment by crimsoncantab** [comment]
Hey @gregstein. Which version of python are you using? Unfortunately I think this code was written for python2, so it will likely break if you're using python3: https://stackoverflow.com/questions/33054527/typeerror-a-bytes-like-object-is-required-not-str-when-writing-to-a-file-in.

Do you have a stacktrace with the line of code where the error occurs?

**Comment by gregstein** [comment]
Hello @crimsoncantab! I hope you're doing well. And thank you for the fast response <3

You're right! I'm using 3.6.8 but I do not mind using py2. Here is the stacktrace you asked for:
![stack](https://user-images.githubusercontent.com/16618729/148754283-f1e1ce0b-3dbf-4751-a0f7-13af131a9ab3.jpg)

I will try with py2 first and see how that works. Thank you!

**Comment by gregstein** [comment]
Oh wow! Thank you so much! on py2 the command worked out of the box. You are truly amazing!

**Comment by gregstein** [comment]
One final question! Can I extract hk_mapping values from hkstrings.py?

**Comment by crimsoncantab** [comment]
Are you wanting to make a json export of hk_mapping? I updated the code on a branch (see above, 
7159c1d) so that running hkstrings.py will print hk_mapping to json.

**Comment by gregstein** [comment]
uhhh! YOU'RE AWESOME! Thank you so much crimson! That's what I needed

**Comment by crimsoncantab** [comment]
Sure thing! Glad I could easily help you. At some point the app needs to be converted to python3, but I haven't found the time to do that. Would be a larger rework to still be deployable to GCP.

**Comment by gregstein** [comment]
I agree with you. And honestly no need to. 
Thank you again crimson <3

Have a great rest of your day.
