### ISSUE TITLE
Hotkeys DE

### ISSUE THREAD

**Issue by fpracing1** [crimsoncantab/aok-hotkeys#75]
Hi. I'm having the next error "File format not recognized: Unrecognized file format, header: 40400000, length: 4904" when I try to convert DE hotkeys to AoC version. Thanks a lot for your work.

**Comment by crimsoncantab** [comment]
@fpracing1 thanks for the heads up. Looks like the latest patch added new hotkeys. I'll get this updated.

**Comment by crimsoncantab** [comment]
@fpracing1 should work now, give it a go. Let me know if there are still issues. *Might* need to clear your browser cache.

**Comment by fpracing1** [comment]
Now it works fine. Thank you!
