### ISSUE TITLE
More Community patch 1.6 Monastery techs possible

### ISSUE THREAD

**Issue by marklig** [crimsoncantab/aok-hotkeys#76]
Could you please add the Community patch 1.6 Monastery tech upgrades of Heresy, Theocracy, Herbal Medicine, Illumination, Block Printing and Redemption to the site? They can be changed in-game 1.6 now, but the game doesn't register some of my keyboard buttons, so that's why I need your site. ;)
Cheers!

**Comment by crimsoncantab** [comment]
Absolutely. Can you include your .hki file, please?

**Comment by marklig** [comment]
https://easyupload.io/8x3jrl
link because github doesn't allow .hki attachments

**Comment by crimsoncantab** [comment]
Great, thanks. I'll get this updated this weekend.

**Comment by crimsoncantab** [comment]
Hmm, @marklig that *.hki file didn't have entry for Monastery techs in it. I'd need a file that has hotkey entries for those techs so I can extract the id used to assign each hotkey. Can you upload again, with those hotkeys set to something?

**Comment by marklig** [comment]
Hmm, strange. I've tried to turn off the overlay and remove foreign keyboard monastery hotkeys now: https://easyupload.io/h7qhxk sorry for slow answer.
![monastery hotkeys](https://user-images.githubusercontent.com/101865547/159187062-58fe6a66-36f4-4223-98c0-8eb9b5aa86e0.png)

**Comment by crimsoncantab** [comment]
Okay thanks for sharing that link. There are still no hotkeys in the 2nd file you shared that are unrecognized by the code. That tells me that CP is re-using existing hotkeys - I still just can't tell which ones.

Here's what worries me: if CP is using some of the same internal codes for these hotkeys that DE or other versions are using for *different* hotkeys, that's a situation that the app doesn't currently handle - it would take some coding to get that working right.

Are you able to make the keybindings more unique - e.g. Alt+F7 or something like that? Then I can tell which hotkey they're getting assigned to. Right now there's too many hotkeys with e.g. the "W" key-binding to tell which one is being used for e.g. Redemption.

**Comment by marklig** [comment]
Sure,  
Redemption: Alt+F7
 Sanctity: Alt+F8
 Illumination: Alt+F12
 Heresy:Ctrl+Alt+F6
 Theocracy:Ctrl+Alt+F5
 Herbal Medicine:Ctrl+Alt+F9
https://easyupload.io/lqccae
![monastery2 hotkeys](https://user-images.githubusercontent.com/101865547/159292530-167f2327-6541-4d91-89e0-581216f42372.png)

**Comment by crimsoncantab** [comment]
Okay, yep, I found em. CP used ids 19116 through 19122 for Monastery tech hotkeys. DE used ids 19120-19125 for various other things. So we have a conflict. You can still edit the hotkeys in the editor, but I'll have to update the site to have both the DE & CP strings for each hotkey. That's kind of a work around for a much more involved solution that would require a lot of changes to support different versions of the game mapping to the same ID independently.
