### ISSUE TITLE
New Voobly update with advancing next Age can't load hki-file

### ISSUE THREAD

**Issue by marklig** [crimsoncantab/aok-hotkeys#79]
Voobly has updated their 1.6RC community patch to include a hotkey for Advancing the next age in the town center.
However, I can't load the new hki-file in the editor at your site. 

> File format not recognized: Unrecognized file format, header: 3f800000, length: 2876

**Comment by crimsoncantab** [comment]
Thanks for reporting this. Could you provide a copy of the *.hki file that is generated by 1.6RC?

**Comment by marklig** [comment]
Ah, yes
https://easyupload.io/m/aq6fgm

**Comment by crimsoncantab** [comment]
Updated. Should work now, please reopen if you run into issues. Note that the hotkey code conflicted with an existing DE hotkey, so I had to merge them:

![image](https://user-images.githubusercontent.com/4349440/192929208-d7bc3f04-eba5-46a5-a26e-c13f702878ce.png)
