### ISSUE TITLE
New voobly update 1.6 RC - jan2023

### ISSUE THREAD

**Issue by marklig** [crimsoncantab/aok-hotkeys#80]
A new 1.6 RC update has been released at voobly - with several new hotkeys available, and breaks the hotkey file. Upload error message: "File format not recognized: Unrecognized file format, header: 3f800000, length: 3520"
v1.6 Game Data is currently listed as 2.4.1 and v1.6 RC is listed as 2.4.3.

In addition to new units such as caravaserrai, they seem to have abandoned the shared hotkey techs, that were covered under the headline **Additional hotkeys for technologies** here https://aoe2de.com/how-to-play/, instead giving each tech a separate hotkey.
https://easyupload.io/itnr21

I filled all the ??? keys with new strokes such as Ctrl + Alt, Ctrl + Alt + Shift, and Alt + F#
![AOK001](https://user-images.githubusercontent.com/101865547/210850121-62d4ea10-8a00-4586-83dd-f6d2556e77fe.png)

**Comment by crimsoncantab** [comment]
Thanks for reporting. Could you upload a .hki file made with the newest
update?

**Comment by marklig** [comment]
it's the https://easyupload.io/itnr21 link

**Comment by crimsoncantab** [comment]
My apologies! I read just the email preview of your message and it looked
like it was just a couple sentences. Sorry I didn't read the whole thing.
Thank you very much for prepping a good hki file that I can use. I'll get
that fixed.

**Comment by marklig** [comment]
No worries! Actually, I missed the last grouping on the left. I think that .hki only contained up to the market group on the left side. So here's a full .hki and corresponding screenshots for what the key presses launches. (Do you need these decodings?) Thanks for your work!

https://easyupload.io/mkjg4c
![AOK004](https://user-images.githubusercontent.com/101865547/210882309-b0306792-5f78-4ffe-9447-fb996a9798d8.png)
![AOK005](https://user-images.githubusercontent.com/101865547/210882313-a0f4a725-cda8-462b-84ca-821f7a29310c.png)
![AOK006](https://user-images.githubusercontent.com/101865547/210882316-5a492ee4-5190-48a2-92b4-b77c8c25c510.png)
![AOK007](https://user-images.githubusercontent.com/101865547/210882318-5baae9ca-c8bb-4a78-a587-53c1281c3e3f.png)
![AOK008](https://user-images.githubusercontent.com/101865547/210882321-cbd2c03f-bf61-4be6-8a3f-344169343172.png)
![AOK009](https://user-images.githubusercontent.com/101865547/210882323-52529c2d-1c28-4e96-b31a-d2cb105cd558.png)
![AOK010](https://user-images.githubusercontent.com/101865547/210882325-0add76a4-9dbd-474d-9493-cdd969fe534a.png)
![AOK011](https://user-images.githubusercontent.com/101865547/210882329-b28734d1-61c7-4a84-ab01-74bed7107be5.png)
![AOK012](https://user-images.githubusercontent.com/101865547/210882330-452098fa-87e1-4dca-b8b9-04d1010e3ee6.png)
![AOK013](https://user-images.githubusercontent.com/101865547/210882331-b7ee6340-a044-440b-87c4-6a1504e024a1.png)
![AOK014](https://user-images.githubusercontent.com/101865547/210882333-5d2a6d9d-fa94-4326-848d-dfae8f2811ce.png)
![AOK015](https://user-images.githubusercontent.com/101865547/210882336-62be6169-a68e-4d25-8f81-0f2bcbc86006.png)
![AOK016](https://user-images.githubusercontent.com/101865547/210882338-40e432ce-4aa4-4d1d-bedf-5bc7939df6c1.png)
![AOK017](https://user-images.githubusercontent.com/101865547/210882340-dd9b1d8a-d325-4f51-96aa-72c4c890a848.png)
![AOK018](https://user-images.githubusercontent.com/101865547/210882345-6877309d-e90e-4edf-a2ba-a910ac7acfa2.png)
![AOK019](https://user-images.githubusercontent.com/101865547/210882347-1b39a02d-ae4f-4318-90d1-ecd94b6cd825.png)
![AOK020](https://user-images.githubusercontent.com/101865547/210882348-28159ddb-e74e-4d8f-9255-605b112ed653.png)
![AOK021](https://user-images.githubusercontent.com/101865547/210882352-fca5b842-ad36-444c-824c-049464b59d1d.png)
![AOK022](https://user-images.githubusercontent.com/101865547/210882354-babfeb21-6723-413e-8895-37fd4c8a063b.png)
![AOK023](https://user-images.githubusercontent.com/101865547/210882357-90068299-84aa-46a6-bfc6-db3ba2560130.png)

**Comment by marklig** [comment]
There's a seemingly new file called hotkey.xml , I've uploaded it to  https://easyupload.io/6neq1k

here's a random line from the file, so you can see if it's interesting:
<Hotkey Name="Arrowslits"             id="0"   langIdText="19126"  langHotKey="16740" />

**Comment by crimsoncantab** [comment]
Looks like it just lists the hotkeys, and has string ids for them. I don't have access to the stringfile for the voobly patch, but the "Name" attribute is somewhat helpful at least for giving me a start.

**Comment by crimsoncantab** [comment]
@marklig thanks for the help! Turned out that that `hotkey.xml` file was a godsend. There were several other hotkeys that clash IDs with DE hotkeys...unfortunately that's kind of clunky to deal with right now, as the code assumes only one hotkey can have a certain ID. so it displays as "{DE Hotkey} | {CP Hotkey}" on the website.

Would you be willing to check the new hotkeys added to make sure they tie out with what CP has? There were several hotkeys in your `player1_voobly_2023_01_05 .hki` file that were showing up as "unassigned" (just zero'd out in the binary file), so I could only work off of what the `hotkeys.xml` was telling me

**Comment by marklig** [comment]
Yeah, sorry for the confusion, the player1_voobly_2023_01_05 .hki is outdated, (https://easyupload.io/itnr21)
use player1_voobly_2023_01_05full.hki (https://easyupload.io/mkjg4c) 
Are there still problems?

**Comment by crimsoncantab** [comment]
@marklig I don't think so; I pushed a fix yesterday. Shoot! I missed your `.hki` file again. No worries, was just a little confusion since the hotkeys didn't match. `hotkey.xml` more than made up for that. The changes are live, so take a look when you have a chance and let me know if you see any bugs (you can reopen this issue).
