### ISSUE TITLE
Doesn't work with AoE2DE on steam (Version 101.102.17051.0)

### ISSUE THREAD

**Issue by habex-ch** [crimsoncantab/aok-hotkeys#82]
Hi there,
It does not work with the current Steam DE version.
I always the the following error:
`File format not recognized: Unrecognized file format, header: 40400000, length: 5012`

**Comment by crimsoncantab** [comment]
Thanks for reporting @habex-ch . There must have been a recent update that added new hotkeys. I will get this fixed.

**Comment by 0nelight** [comment]
I opend a new Issue https://github.com/crimsoncantab/aok-hotkeys/issues/84 for the new .hkp File-Structure because the author of this Issue refers to Version 81058 with the old hki format.
