### ISSUE TITLE
Website returns 404

### ISSUE THREAD

**Issue by Patchnote-v2** [crimsoncantab/aok-hotkeys#85]
As the title says, the site (https://aokhotkeys.appspot.com/) is giving a page not found.  I'm not sure when this started, but it would be within the past couple months.

![image](https://github.com/crimsoncantab/aok-hotkeys/assets/11915225/780e03a1-cac3-49e8-b4e9-371bc6d2605b)

**Comment by crimsoncantab** [comment]
Site is back up. I took the site down while dealing with some billing issues. Are people still finding value in it? The site does not work for most recent versions of DE, so I'm assuming people are using it for older versions of the game? I can keep paying to host it, but don't have the time to get it working with the new stuff.

**Comment by Patchnote-v2** [comment]
For what it's worth, the code itself has been extremely helpful.  Using the code you wrote to parse HKI/HKP files, as well as the work in issue #84 done by @KSneijders, I developed what I hope can be a successor site.

I chose to only support build 83607 and onwards since that's the update that split the hotkey files.  You can see the repo on my profile if you're interested.  It's entirely complete and has been live for a few months, I've just been apprehensive to start advertising it on places like the AoE2 subreddit or Discord since I'm sure it will expose all the bugs, not to mention it's not nearly as lightweight as a site like yours, haha.

**Comment by crimsoncantab** [comment]
> For what it's worth, the code itself has been extremely helpful. Using the code you wrote to parse HKI/HKP files, as well as the work in issue #84 done by @KSneijders, I developed what I hope can be a successor site.
> 
> I chose to only support build 83607 and onwards since that's the update that split the hotkey files. You can see the repo on my profile if you're interested. It's entirely complete and has been live for a few months, I've just been apprehensive to start advertising it on places like the AoE2 subreddit or Discord since I'm sure it will expose all the bugs, not to mention it's not nearly as lightweight as a site like yours, haha.

Hey, this site is awesome! I will get a link to it from the legacy site so DE players know where to go. Good work!
